SET IDENTITY_INSERT [dbo].[PRODUTOS] ON
INSERT INTO [dbo].[PRODUTOS] ([ID_PRODUTO], [NOME], [QUANTIDADE], [QUANTIDADE_STOCK], [PRECO], [MODELO]) VALUES (1, N'Iogurte de morango', 4, 1000, CAST(1.0000 AS Money), N'M-455')
INSERT INTO [dbo].[PRODUTOS] ([ID_PRODUTO], [NOME], [QUANTIDADE], [QUANTIDADE_STOCK], [PRECO], [MODELO]) VALUES (2, N'Iogurte de ananás', 4, 1500, CAST(1.0000 AS Money), N'M-456')
INSERT INTO [dbo].[PRODUTOS] ([ID_PRODUTO], [NOME], [QUANTIDADE], [QUANTIDADE_STOCK], [PRECO], [MODELO]) VALUES (3, N'Iogurte liquido de morango', 4, 2000, CAST(1.5000 AS Money), N'M-100')
INSERT INTO [dbo].[PRODUTOS] ([ID_PRODUTO], [NOME], [QUANTIDADE], [QUANTIDADE_STOCK], [PRECO], [MODELO]) VALUES (5, N'Gelatina morango', 8, 500, CAST(0.8000 AS Money), N'M-600')
INSERT INTO [dbo].[PRODUTOS] ([ID_PRODUTO], [NOME], [QUANTIDADE], [QUANTIDADE_STOCK], [PRECO], [MODELO]) VALUES (6, N'Gelatina Limão', 4, 200, CAST(0.0800 AS Money), N'M-601')
SET IDENTITY_INSERT [dbo].[PRODUTOS] OFF
