INSERT INTO [dbo].[LINHA_SUG_REC] ([ID_SUG_REC], [ID_FUNCIONARIO], [ID_CLIENTE], [DEPARTAMENTO], [ESTADO_RESOLUCAO]) VALUES (1, 3, 3, N'Reclamações', N'Em análise')
INSERT INTO [dbo].[LINHA_SUG_REC] ([ID_SUG_REC], [ID_FUNCIONARIO], [ID_CLIENTE], [DEPARTAMENTO], [ESTADO_RESOLUCAO]) VALUES (4, 5, 6, N'Financeira', N'Concluida')
INSERT INTO [dbo].[LINHA_SUG_REC] ([ID_SUG_REC], [ID_FUNCIONARIO], [ID_CLIENTE], [DEPARTAMENTO], [ESTADO_RESOLUCAO]) VALUES (3, 5, 4, N'Reclamações', N'Concluida')
